// Light-hearted, automotive/AUTOSAR-themed quips shown (at random) while the
// ingestion step builds the knowledge base. Purely cosmetic — the real signal
// is the /status poll. There are 100 of them so the demo rarely repeats itself.
export const INGEST_JOKES: readonly string[] = [
  'Bribing the ECUs to cooperate…',
  'Untangling the wiring harness…',
  'Teaching the Door component about boundaries…',
  'Counting signals, losing count, starting over…',
  'Negotiating with the CAN bus…',
  "Parsing ARXML so you don't have to…",
  'Following signal chains down the rabbit hole…',
  'Reticulating splines…',
  'Convincing the brakes they are load-bearing…',
  'Mapping ports to ports to even more ports…',
  'Warming up the blast-radius calculator…',
  'Asking the AUTOSAR oracle for a second opinion…',
  "Explaining to the gateway why it's a gateway…",
  "Decoding hex like it's a cryptic crossword…",
  'Politely asking the watchdog not to bite…',
  'Herding 4,000 signals into a single lane…',
  'Translating German abbreviations back into German…',
  'Convincing the BSW it is, in fact, basic…',
  'Looking for the RTE in all the wrong places…',
  'Counting CAN frames, one beep at a time…',
  'Persuading the diagnostic stack to diagnose itself…',
  'Defragmenting the wiring loom…',
  'Teaching the infotainment system some manners…',
  'Aligning the torque on every bolt of code…',
  'Whispering sweet nothings to the flash memory…',
  'Rebooting the coffee-machine ECU (priorities)…',
  'Asking the SWC where it parked…',
  'Resolving port references the hard way…',
  'Measuring the blast radius in door handles…',
  'Untwisting the twisted pair…',
  "Verifying the brake light still means 'stop'…",
  'Convincing two ECUs to share one bus politely…',
  'Sorting interfaces alphabetically, then regretting it…',
  'Checking if the airbag is just shy…',
  'Petting the bus-off error until it calms down…',
  "Re-deriving Ohm's law, just to be safe…",
  'Counting the ways a Door can break…',
  'Mapping the composition tree without a ladder…',
  "Convincing the CAN bus it isn't a CAN't bus…",
  "Asking each signal where it's going in life…",
  'Negotiating bit timing over coffee…',
  'Untangling spaghetti — the architectural kind…',
  'Looking both ways before crossing the data flow…',
  'Reminding the ECU that 255 is not infinity…',
  'Calibrating the calibration that calibrates…',
  'Checking the manual nobody read…',
  'Teaching old ARXML new tricks…',
  'Inventing units for things that should be unitless…',
  "Convincing diagnostics there's nothing to diagnose…",
  'Lubricating the state machine…',
  'Asking the bootloader to please boot faster…',
  'Triangulating the source of one mysterious signal…',
  'Counting components on its fingers…',
  'Reassuring the EDC that everyone gets nervous…',
  'Refactoring the wiring, one wire at a time…',
  'Reading 1,392 lines so you can read zero…',
  'Sorting 39 platform types into 39 little boxes…',
  'Double-checking that left is not right…',
  'Confirming the left door is, in fact, on the left…',
  'Asking the harness clip to hold on tight…',
  'Looking for meaning in a 32-bit integer…',
  'Coaxing the signal chain out of its shell…',
  'Teaching the ECU object permanence…',
  'Convincing the bus to share the road…',
  'Counting dependencies until they count back…',
  'Greasing the message queue…',
  "Tuning the idle so the demo doesn't stall…",
  'Asking the compiler nicely, then begging…',
  'Following the dependency graph to its lair…',
  'Reminding the timer it has one job…',
  'Polishing each port until it shines…',
  "Translating 'works on my bench' to production…",
  'Checking the torque specs of the codebase…',
  'Aligning the stars and the signal timings…',
  'Convincing the door it can close without drama…',
  'Counting electrons, rounding generously…',
  'Asking the CAN bus to merge without honking…',
  'Reverse-engineering the reverse gear…',
  'Persuading the ECU to share its feelings (and logs)…',
  'Indexing every element twice, to be sure…',
  'Negotiating a ceasefire between two gateways…',
  'Reading the schematic upside down, then right-side up…',
  'Counting unresolved references (zero, fingers crossed)…',
  "Whispering to the harness: 'you can do this'…",
  'Mapping signal chains like a detective board…',
  'Checking whether the EDC ECU had its coffee…',
  'Asking the platform types to please be consistent…',
  'Convincing the validator that PASS means pass…',
  'Untangling one more wire… okay, two more…',
  'Teaching the interfaces to interface…',
  "Courting the demo gods' favor…",
  'Counting components: 1, 2, 3, 4, done…',
  'Asking the system extract to extract faster…',
  'Reassembling the architecture from memory…',
  "Convincing the door control it's in control…",
  'Verifying gravity still applies to dropped frames…',
  'Aligning every signal to true north…',
  'Reading the ARXML so slowly it feels fast…',
  "Telling the watchdog it's a good boy…",
  'Almost there — pretending the last 10% is easy…',
];

// Return a random index different from `current` so the line always changes.
export function nextRandomJokeIndex(current: number, length = INGEST_JOKES.length): number {
  if (length <= 1) return 0;
  let next = current;
  while (next === current) {
    next = Math.floor(Math.random() * length);
  }
  return next;
}
